### ISSUE TITLE
[4.0] Next major version

### ISSUE THREAD

**Issue by frederikbosch** [moneyphp/money#393]
This issue will contain a list of suggestions that we could take into account for the next major version of this library. Ideas are not complete in the sense that they represent what are going to do. It is merely a place where we can collect idea.

Ideas.
- [x] Parser should accept Currency object, see #386.
- [ ] ISOCurrencies could have a `loader` interface injected, possible implementations are StaticLoader, DirectLoader and CachableLoader, see #392.
- [ ] Move calculators to a `CalculatorRegistry` that can be used by Money and other classes that require calculations, see #384 and #363.
- [ ] Implementation of PreciseMoney, see #7 and #335.
- [x] Move towards PHP 7.1+ with string and return types and less docblock.

In order to have your ideas listed, please open an issue for discussion. If there is agreement that it should be taken into account in the major next version, we will list it here.

**Comment by sagikazarmark** [comment]
I think some of them can be implemented in a BC manner in this version as well, and remove the unwanted behaviour in the next major. Parser and CalculatorRegistry can surely be done this way.

**Comment by frederikbosch** [comment]
@sagikazarmark True. I rather go for everything in the next major version. I would be more than happy to give the first shot at this and move everything towards PHP 7.1 code.

**Comment by sagikazarmark** [comment]
Yeah, me too, but I would like to avoid maintaining two versions and we've just released Money 3.0, so people using it would probably not want to migrate again.

So as long as we have to maintain 3.0 I would rather pack the new features in it as long as possible.

**Comment by sagikazarmark** [comment]
@frederikbosch I know you worked on Precise Money a lot, but I think it would be better to aim that for 4.1

Let's make 4.0 about removing deprecations and moving to 7.1. WDYT?
