### ISSUE TITLE
[3.1] tracking issue

### ISSUE THREAD

**Issue by frederikbosch** [moneyphp/money#424]
The following issues have to be resolved before issuing 3.1.
- [x] [Fix StyleCI](https://github.com/moneyphp/money/issues/426)
- [x] [Conversion result is always 0 when subunit difference is large enough](https://github.com/moneyphp/money/issues/425)
- [x] [Unexpected result when converting small bitcoin amounts](https://github.com/moneyphp/money/issues/422)
- [x] [BitcoinMoneyFormatter is not locale aware](https://github.com/moneyphp/money/issues/412)
- [x] [Remove support for string currencies](https://github.com/moneyphp/money/issues/397)
- [x] [Remove support for string currencies](https://github.com/moneyphp/money/issues/386)
- [x] [Allocation of money works wrong when one of ratio equals to 0](https://github.com/moneyphp/money/issues/436)

The following PRs have to be closed/resolved/merged before issuing 3.1.
- [x] [Add a few more test cases to currency conversion](https://github.com/moneyphp/money/pull/423)
- [x] [Add a comparator for use in PHPUnit tests](https://github.com/moneyphp/money/pull/416)
- [x] [~~typehints for static methods~~](https://github.com/moneyphp/money/pull/415)
- [x] [~~support instantiating money from float~~](https://github.com/moneyphp/money/pull/410)
- [x] [Modulus support](https://github.com/moneyphp/money/pull/400)
- [x] [Add a class in order for the developer to instantiate his own Currencies](https://github.com/moneyphp/money/pull/391)
- [x] [~~Correct scale for add/subtract~~](https://github.com/moneyphp/money/pull/378)
- [x] [add ratioOf method](https://github.com/moneyphp/money/pull/439)
- [x] [PHPUnit upgrade](https://github.com/moneyphp/money/pull/440)
- [x] [Intl Localized Decimal Formatter/Parser](https://github.com/moneyphp/money/pull/443)

**Comment by frederikbosch** [comment]
Ah, I just found out about github milestones, which @sagikazarmark has already created for 3.1.0.

**Comment by sagikazarmark** [comment]
Yeah, I usually prefer milestones for these kind of things.

**Comment by frederikbosch** [comment]
Ready to release 3.1 if you ask me.

**Comment by frederikbosch** [comment]
Uh, I added a new PR `ratioOf`. I'd be very happy to have it merged and included in 3.1.

**Comment by frederikbosch** [comment]
@sagikazarmark In my opinion we are ready to release 3.1. If you can have a look at the ratioOf PR, I'd be very happy.

**Comment by frederikbosch** [comment]
Already merged the `ratioOf` method. That leaves the final #440 as final todo.

**Comment by frederikbosch** [comment]
Added version 3.1.0 to the changelog. Ready to release after we cleared #440 and have a corresponding green light on Travis.

**Comment by frederikbosch** [comment]
Since all PRs are merged, Travis is green, I am going to close this one. Release is up for next Monday.

**Comment by frederikbosch** [comment]
@sagikazarmark I saw your remark on the changelog, good catch. Are we good to go with the release in your opinion?

**Comment by sagikazarmark** [comment]
Yup, tagged the new version.
